env:
  browser: true
  es2021: true
  jest: true
extends:
  - eslint:recommended
  - plugin:react/jsx-runtime
  - plugin:@typescript-eslint/recommended
overrides: []
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: latest
  sourceType: module
plugins:
  - react
  - '@typescript-eslint'
  - 'react-hooks'
rules:
  react-hooks/rules-of-hooks:
    - error
  react-hooks/exhaustive-deps:
    - error
  indent:
    - error
    - 2
  linebreak-style:
    - error
    - unix
  quotes:
    - error
    - single
  semi:
    - error
    - never

