name: BuildTestLint
run-name: Building Testing Linting.
on:
  - push
  - pull_request
jobs:
  install-cache:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 19.x ]
    steps:
      - name: Checkout Commit
        uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node }}
        uses: actions/setup-node@v3

      - name: Cache node modules
        uses: actions/cache@v3
        id: cache-npm
        env:
          cache-name: cache-node-modules
        with:
          path: node_modules
          key: ${{ runner.os }}-npm-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-npm-

      - if: ${{ steps.cache-npm.outputs.cache-hit != 'true' }}
        run: |
          npm ci
      - name: run build
        run: npm run build:prod
      - name: build storybook
        run: npm run storybook:build
      - name: test unit
        run: npm run test:unit
      - name: test ui (storybook screenshots)

        run: npm run test:ui:ci

  lint-format:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [19]
    needs: install-cache
    steps:
      - name: Checkout Commit
        uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
      - name: Restore yarn dependencies
        uses: actions/cache@v3
        id: cache-dependencies
        with:
          path: node_modules
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - name: Run lint
        run: |
          npm run lint:ts
      - name: Run prettier
        run: |
          npm run lint:scss



