name: BuildTestLint
run-name: Building Testing Linting.
on:
  - push
  - pull_request
jobs:
  install-cache:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 19.x ]
    steps:
      - name: Checkout Commit
        uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node }}
        uses: actions/setup-node@v3

      - name: Cache node modules
        uses: actions/cache@v3
        id: cache-npm
        env:
          cache-name: cache-node-modules
        with:
          path: node_modules
          key: ${{ runner.os }}-npm-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-npm-

      - if: steps.cache-dependencies.outputs.cache-hit != 'true'
        run: |
          npm ci
      - name: run build
        run: npm run build:prod
      - name: lint ts and tsx
        run: npm run lint:ts
      - name: lint style scss
        run: npm run lint:scss
      - name: test unit
        run: npm run test:unit
      - name: build storybook
        run: npm run storybook:build
      - name: test ui (screenshots)
        run: npm run test:ui:ci

#  build:
#    runs-on: ubuntu-latest
#    needs: install-cache
#    strategy:
#      matrix:
#        node-version: [ 19.x ]
#    steps:
#      - uses: actions/checkout@v3
#      - name: Use Node.js ${{ matrix.node-version }}
#        uses: actions/setup-node@v3
#        with:
#          node-version: ${{ matrix.node-version }}
#      - name: Restore npm dependencies
#        uses: actions/cache@v3
#        id: cache-dependencies
#        with:
#          path: ~/.npm
#          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
#          restore-keys: |
#            ${{ runner.os }}-build-${{ env.cache-name }}-
#            ${{ runner.os }}-build-
#            ${{ runner.os }}-
#      - name: Run build
#        run: |
#          npm run build:prod
#      - name: lint ts and tsx
#        run: npm run lint:ts
#      - name: lint style scss
#        run: npm run lint:scss
#      - name: test unit
#        run: npm run test:unit
#      - name: build storybook
#        run: npm run storybook:build
#      - name: test ui (screenshots)
#        run: npm run test:ui:ci


