name: BuildTestLint
run-name: Building Testing Linting
on:
  - push
  - pull_request
jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [ 19.x ]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - name: install modules
        run: npm ci
      - name: build prod version of project
        run: npm run build:prod
      - name: lint ts and tsx
        run: npm run lint:ts
      - name: lint style scss
        run: npm run lint:scss
      - name: test unit
        run: npm run test:unit
      - name: build storybook
        run: npm run storybook:build
      - name: test ui (screenshots)
        run: npm run test:ui:cd


